[features]
seeds = true
skip-lint = false

[programs.localnet]
leaderboards = "C2WzwqdpPaiRP6H9C11331nLhyKtq2WA7hse25ajvJyb"
delegator = "9NyqaDMnzDXDXRKW9uBnQSHmUUAQZh4VKj4d8dvECbKJ"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "./tests/genesis/mpl_token_metadata.so"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "./tests/keypairs/test.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test-token = "yarn run ts-node scripts/testToken.ts"
forest = "yarn run ts-node scripts/createForest.ts"