[features]
seeds = true
skip-lint = false

[programs.localnet]
dippies_index_protocol = "GrwRJ5fgKwethiy3Zf5rAYuYJVv938FT3N4hiwV71H8K"

[registry]
url = "https://api.apr.dev"


[provider]
cluster = "localnet"
wallet = "./tests/keypairs/test.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test-token = "yarn run ts-node scripts/testToken.ts"
forest = "yarn run ts-node scripts/createForest.ts"