[features]
seeds = true
skip-lint = false

[programs.localnet]
dippies_index_protocol = "C2WzwqdpPaiRP6H9C11331nLhyKtq2WA7hse25ajvJyb"
delegator = "9NyqaDMnzDXDXRKW9uBnQSHmUUAQZh4VKj4d8dvECbKJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "./tests/keypairs/test.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test-token = "yarn run ts-node scripts/testToken.ts"
forest = "yarn run ts-node scripts/createForest.ts"