[features]
seeds = true
skip-lint = false

[programs.localnet]
dippies_index_protocol = "7rxT36fYNGHB1hfXstL79FaFuVgZXzYCiM7yVJ7cdipD"

[registry]
url = "https://api.apr.dev"


[provider]
cluster = "localnet"
wallet = "./tests/keypairs/test.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test-token = "yarn run ts-node scripts/testToken.ts"
root = "yarn run ts-node scripts/createRoot.ts"